// Structured security audit log. Every line is JSON, written to the process
// console (visible in Render's log viewer) and appended to AUDIT_LOG_FILE.
// Covers the OWASP "Logging and Auditing" requirements: successful/failed
// logins, lockouts, account events and admin mutations.
//
// Redaction rule: NEVER log passwords, codes, tokens, or full bodies — the
// event name plus a few scalar identifiers only.
//
// PERSISTENCE (Render-safe): Render's filesystem is ephemeral — every deploy
// wiped the audit file, so the trail restarted empty and scan/log events
// seemed to vanish. The admin /api/audit-trail endpoint reads ONLY this file
// (synchronously), so the file must always exist. The fix keeps the file as
// the primary store and adds an optional durable remote sink:
//
//   AUDIT_REMOTE_URL   e.g. https://<project>.supabase.co/rest/v1
//   AUDIT_REMOTE_KEY   service key for that REST endpoint
//   AUDIT_REMOTE_TABLE (default "audit_log")
//
//   - audit() mirrors every line to the remote table (best-effort, never
//     blocks or fails a request; failures are throttled, not silent-spammy).
//   - At boot, reSeedFromRemote() pulls the remote snapshot back into the
//     local file (skip-if-present, line-merged) so GET /api/audit-trail shows
//     the full history even right after a redeploy on a fresh container.
//   - SQL to create the table (run once in the Supabase SQL editor):
//       create table if not exists audit_log (
//         id bigint generated by default as identity primary key,
//         created_at timestamptz not null default now()
//       );
//     Rows themselves are stored as one jsonb column "data".
//   - No Supabase SDK: plain global fetch (Node 18+), zero new dependencies.
const fs = require('node:fs');
const path = require('node:path');

// The audit file is the PRIMARY store — the admin /api/audit-trail endpoint
// reads it back, so it must always exist, not only when an operator remembers
// to set an env var (that was the bug: on Render nothing set AUDIT_LOG_FILE,
// so no file was ever written and the admin page showed an empty trail).
// Default: alongside the database/data files (INVENTRAK_DATA_DIR when set,
// so isolated/test instances keep their trail in their own data dir).
// Override with AUDIT_LOG_FILE.
const DEFAULT_DATA_DIR = process.env.INVENTRAK_DATA_DIR || path.join(__dirname, '..', 'data');
const AUDIT_LOG_FILE = process.env.AUDIT_LOG_FILE || path.join(DEFAULT_DATA_DIR, 'audit.log');

// ---- Remote sink (optional) ------------------------------------------------
const REMOTE_URL = (process.env.AUDIT_REMOTE_URL || '').replace(/\/+$/, '');
const REMOTE_KEY = process.env.AUDIT_REMOTE_KEY || '';
const REMOTE_TABLE = process.env.AUDIT_REMOTE_TABLE || 'audit_log';
const remoteEnabled = Boolean(REMOTE_URL && REMOTE_KEY);

let remoteFailCount = 0;
let lastRemoteWarnAt = 0;

// Mirror one audit line to the remote table. Best-effort: a remote outage
// must never slow down or break the request that produced the event. Warn
// at most every 5 minutes no matter how many writes fail.
async function mirrorToRemote(entry) {
  if (!remoteEnabled) return;
  try {
    const res = await fetch(`${REMOTE_URL}/${REMOTE_TABLE}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Prefer': 'return=minimal',
        'apikey': REMOTE_KEY,
        'Authorization': `Bearer ${REMOTE_KEY}`,
      },
      body: JSON.stringify({ created_at: entry.t, data: entry }),
    });
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    remoteFailCount = 0;
  } catch (err) {
    remoteFailCount += 1;
    const now = Date.now();
    if (now - lastRemoteWarnAt > 5 * 60 * 1000) {
      console.error(`[audit] remote sink unavailable (${remoteFailCount} failed writes): ${err.message}`);
      lastRemoteWarnAt = now;
    }
  }
}

// Boot-time re-seed: pull the remote snapshot into the local file so the
// (synchronous, file-reading) /api/audit-trail endpoint serves the full
// history even on a brand-new container right after a deploy. Skip-if-present:
// entries whose `t` (ISO timestamp) already exist locally are not duplicated,
// so restarts and multiple instances never double-write.
async function reSeedFromRemote() {
  if (!remoteEnabled) return { ok: false, reason: 'remote sink not configured' };
  try {
    // Order ascending so the file stays chronological (readers reverse it).
    const res = await fetch(
      `${REMOTE_URL}/${REMOTE_TABLE}?select=created_at,data&order=created_at.asc&limit=5000`,
      { headers: { 'apikey': REMOTE_KEY, 'Authorization': `Bearer ${REMOTE_KEY}` } },
    );
    if (!res.ok) throw new Error(`HTTP ${res.status}`);
    const rows = await res.json();
    const existing = new Set(
      fs.existsSync(AUDIT_LOG_FILE)
        ? fs.readFileSync(AUDIT_LOG_FILE, 'utf8').split('\n').filter(Boolean)
            .map((line) => { try { return JSON.parse(line).t; } catch { return null; } })
            .filter(Boolean)
        : [],
    );
    let appended = 0;
    const newLines = [];
    for (const row of rows || []) {
      const entry = row && row.data;
      if (!entry || !entry.t || existing.has(entry.t)) continue;
      newLines.push(JSON.stringify(entry));
      existing.add(entry.t);
      appended += 1;
    }
    if (newLines.length > 0) {
      fs.mkdirSync(path.dirname(AUDIT_LOG_FILE), { recursive: true });
      fs.appendFileSync(AUDIT_LOG_FILE, newLines.join('\n') + '\n');
    }
    console.log(`[audit] remote snapshot: ${appended} new entr${appended === 1 ? 'y' : 'ies'} re-seeded into ${AUDIT_LOG_FILE}`);
    return { ok: true, appended };
  } catch (err) {
    console.error(`[audit] remote snapshot re-seed failed: ${err.message}`);
    return { ok: false, reason: err.message };
  }
}

// ---- Core audit write ------------------------------------------------------

// Defense in depth: even if a caller slips a sensitive field into `details`,
// it is stripped before the line is written. Never trust the caller.
const SENSITIVE_KEYS = new Set([
  'password',
  'pass',
  'token',
  'mfaToken',
  'idToken',
  'secret',
  'mfa_secret',
  'code',
  'verificationCode',
  'resetCode',
  'authorization',
  'cookie',
  'apiKey',
]);

function redact(details) {
  const clean = {};
  for (const [k, v] of Object.entries(details || {})) {
    if (SENSITIVE_KEYS.has(String(k).toLowerCase())) continue;
    clean[k] = v;
  }
  return clean;
}

function audit(event, details = {}) {
  const line = JSON.stringify({
    t: new Date().toISOString(),
    event,
    ...redact(details),
  });
  // Render log viewer picks this up; local dev sees it too.
  console.log(`[audit] ${line}`);
  if (AUDIT_LOG_FILE) {
    try {
      fs.mkdirSync(path.dirname(AUDIT_LOG_FILE), { recursive: true });
      fs.appendFileSync(AUDIT_LOG_FILE, line + '\n');
    } catch {
      // Logging must never take the request down.
    }
  }
  // Fire-and-forget durable copy (no-op unless the remote sink is configured).
  try {
    mirrorToRemote(JSON.parse(line));
  } catch {
    // Never let mirroring break the caller.
  }
}

module.exports = { audit, AUDIT_LOG_FILE, reSeedFromRemote };
