-- Durable audit trail (run ONCE in the Supabase SQL Editor).
--
-- Why: Render's filesystem is ephemeral — every deploy wiped audit.log, so
-- GET /api/audit-trail (and the Audit Trail page) restarted empty and scan
-- events seemed to vanish. The backend now mirrors every audit line to this
-- table (best-effort) and re-seeds the local file from it at boot.
--
-- Wired to the backend automatically. Running this SQL IS the whole setup:
-- audit.js derives its sink from the Supabase driver config the app already
-- has, so there is no env var to add and no secret to paste.
--
--   SUPABASE_URL + SUPABASE_KEY  (already set on inventrak-api)
--       -> https://<ref>.supabase.co/rest/v1 + service_role key
--
-- Optional overrides (rare — only to point the trail at a DIFFERENT project
-- than the data):
--   AUDIT_REMOTE_URL   = https://<other-ref>.supabase.co/rest/v1
--   AUDIT_REMOTE_KEY   = that project's service_role secret
--   AUDIT_REMOTE_TABLE = audit_log (optional — this is the default)
--
-- Check status without a dashboard: GET /api/meta -> .audit
--
-- If the table does not exist, the backend still works exactly as before
-- (file only) — the mirror is best-effort and only warns, throttled to once
-- every 5 minutes.
--
-- Storage shape: one row per audit event — the full JSON entry (t, event,
-- actor, actorRole, kind, target_id, payload, ...) lives in a single jsonb
-- "data" column, mirroring the lines in audit.log. created_at is kept as a
-- real column for ordering/retention and matches the entry's "t" timestamp.

create table if not exists audit_log (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  data jsonb not null
);

-- The backend reads newest-last ascending with a 5000-row cap at boot and
-- writes single inserts; this index keeps both cheap.
create index if not exists audit_log_created_at_idx on audit_log (created_at desc);

-- Row-level security: the backend writes with the service_role key (which
-- bypasses RLS), so no policies are added — anon/authenticated keys get
-- nothing. Only the server and dashboard queries run with the service key.

-- Optional retention (uncomment to keep ~90 days):
-- delete from audit_log where created_at < now() - interval '90 days';
